[2024-03-05T20:54:17.503+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:17.507+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:17.507+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T20:54:17.514+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-06-01 00:00:00+00:00
[2024-03-05T20:54:17.517+0000] {standard_task_runner.py:60} INFO - Started process 262 to run task
[2024-03-05T20:54:17.519+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-06-01T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpa52zr3e0']
[2024-03-05T20:54:17.520+0000] {standard_task_runner.py:88} INFO - Job 17: Subtask download_dataset
[2024-03-05T20:54:17.545+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T20:54:17.569+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-05T20:54:17.584+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-01T00:00:00+00:00'
[2024-03-05T20:54:17.585+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-05T20:54:17.586+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh 2023 06']
[2024-03-05T20:54:17.591+0000] {subprocess.py:86} INFO - Output:
[2024-03-05T20:54:17.592+0000] {subprocess.py:93} INFO - 
[2024-03-05T20:54:17.592+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/06
[2024-03-05T20:54:17.592+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/06
[2024-03-05T20:54:17.593+0000] {subprocess.py:93} INFO - /opt/***/include/download_bike_dataset.sh: 14: wget: Permission denied
[2024-03-05T20:54:17.594+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-05T20:54:17.598+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-05T20:54:17.601+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230601T000000, start_date=20240305T205417, end_date=20240305T205417
[2024-03-05T20:54:17.607+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 17 for task download_dataset (Bash command failed. The command returned a non-zero exit code 1.; 262)
[2024-03-05T20:54:17.610+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T20:54:17.622+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:12:48.635+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:48.640+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:48.640+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T21:12:48.648+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-06-01 00:00:00+00:00
[2024-03-05T21:12:48.651+0000] {standard_task_runner.py:60} INFO - Started process 797 to run task
[2024-03-05T21:12:48.652+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-06-01T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpulz3izg8']
[2024-03-05T21:12:48.654+0000] {standard_task_runner.py:88} INFO - Job 47: Subtask download_dataset
[2024-03-05T21:12:48.677+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:12:48.699+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:48.699+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:48.703+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230601T000000, start_date=20240305T211248, end_date=20240305T211248
[2024-03-05T21:12:48.709+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 47 for task download_dataset ('str object' has no attribute 'strftime'; 797)
[2024-03-05T21:12:48.744+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:12:48.758+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T13:27:12.013+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [queued]>
[2024-03-06T13:27:12.018+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [queued]>
[2024-03-06T13:27:12.018+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-06T13:27:12.025+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-06-01 00:00:00+00:00
[2024-03-06T13:27:12.027+0000] {standard_task_runner.py:60} INFO - Started process 515 to run task
[2024-03-06T13:27:12.029+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-06-01T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpydieza9c']
[2024-03-06T13:27:12.030+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask download_dataset
[2024-03-06T13:27:12.054+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-06-01T00:00:00+00:00 [running]> on host 45431f0a53e1
[2024-03-06T13:27:12.086+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-06T13:27:12.104+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-06-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-01T00:00:00+00:00'
[2024-03-06T13:27:12.105+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-06T13:27:12.105+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 07']
[2024-03-06T13:27:12.110+0000] {subprocess.py:86} INFO - Output:
[2024-03-06T13:27:12.111+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:27:12.112+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/07
[2024-03-06T13:27:12.116+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-06T13:27:12.116+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-06T13:27:14.122+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  4 3396k    4  137k    0     0   105k      0  0:00:32  0:00:01  0:00:31  105k100 3396k  100 3396k    0     0  1692k      0  0:00:02  0:00:02 --:--:-- 1692k
[2024-03-06T13:27:14.123+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:27:14.123+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-06T13:27:14.123+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-06T13:27:14.135+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230601T000000, start_date=20240306T132712, end_date=20240306T132714
[2024-03-06T13:27:14.168+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T13:27:14.180+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
