[2024-03-05T20:54:07.419+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:07.423+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:07.423+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T20:54:07.431+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-03-01 00:00:00+00:00
[2024-03-05T20:54:07.434+0000] {standard_task_runner.py:60} INFO - Started process 232 to run task
[2024-03-05T20:54:07.435+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmp_4v1g95e']
[2024-03-05T20:54:07.436+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask download_dataset
[2024-03-05T20:54:07.461+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T20:54:07.487+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-05T20:54:07.504+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-01T00:00:00+00:00'
[2024-03-05T20:54:07.505+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-05T20:54:07.506+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh 2023 03']
[2024-03-05T20:54:07.510+0000] {subprocess.py:86} INFO - Output:
[2024-03-05T20:54:07.512+0000] {subprocess.py:93} INFO - 
[2024-03-05T20:54:07.512+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/03
[2024-03-05T20:54:07.512+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/03
[2024-03-05T20:54:07.513+0000] {subprocess.py:93} INFO - /opt/***/include/download_bike_dataset.sh: 14: wget: Permission denied
[2024-03-05T20:54:07.513+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-05T20:54:07.519+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-05T20:54:07.521+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230301T000000, start_date=20240305T205407, end_date=20240305T205407
[2024-03-05T20:54:07.528+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task download_dataset (Bash command failed. The command returned a non-zero exit code 1.; 232)
[2024-03-05T20:54:07.567+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T20:54:07.581+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:12:37.552+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:37.557+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:37.557+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T21:12:37.564+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-03-01 00:00:00+00:00
[2024-03-05T21:12:37.567+0000] {standard_task_runner.py:60} INFO - Started process 774 to run task
[2024-03-05T21:12:37.569+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpys2bcj7x']
[2024-03-05T21:12:37.570+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask download_dataset
[2024-03-05T21:12:37.597+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:12:37.619+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:37.620+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:37.624+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230301T000000, start_date=20240305T211237, end_date=20240305T211237
[2024-03-05T21:12:37.630+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task download_dataset ('str object' has no attribute 'strftime'; 774)
[2024-03-05T21:12:37.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:12:37.673+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T13:26:56.863+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2024-03-06T13:26:56.868+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [queued]>
[2024-03-06T13:26:56.868+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-06T13:26:56.875+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-03-01 00:00:00+00:00
[2024-03-06T13:26:56.877+0000] {standard_task_runner.py:60} INFO - Started process 491 to run task
[2024-03-06T13:26:56.879+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-03-01T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpa974i67p']
[2024-03-06T13:26:56.880+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask download_dataset
[2024-03-06T13:26:56.905+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-03-01T00:00:00+00:00 [running]> on host 45431f0a53e1
[2024-03-06T13:26:56.936+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-06T13:26:56.955+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-03-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-01T00:00:00+00:00'
[2024-03-06T13:26:56.955+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-06T13:26:56.956+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 04']
[2024-03-06T13:26:56.961+0000] {subprocess.py:86} INFO - Output:
[2024-03-06T13:26:56.962+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:26:56.962+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/04
[2024-03-06T13:26:56.967+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-06T13:26:56.967+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-06T13:26:58.616+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0 2460k    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 32 2460k   32  792k    0     0   563k      0  0:00:04  0:00:01  0:00:03  563k100 2460k  100 2460k    0     0  1492k      0  0:00:01  0:00:01 --:--:-- 1491k
[2024-03-06T13:26:58.618+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:26:58.618+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-06T13:26:58.618+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-06T13:26:58.630+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230301T000000, start_date=20240306T132656, end_date=20240306T132658
[2024-03-06T13:26:58.657+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T13:26:58.666+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
