[2024-03-05T20:54:28.629+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:28.633+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:28.634+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T20:54:28.640+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-09-01 00:00:00+00:00
[2024-03-05T20:54:28.643+0000] {standard_task_runner.py:60} INFO - Started process 291 to run task
[2024-03-05T20:54:28.645+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-09-01T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpbaisslut']
[2024-03-05T20:54:28.646+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask download_dataset
[2024-03-05T20:54:28.670+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T20:54:28.694+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-05T20:54:28.710+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-01T00:00:00+00:00'
[2024-03-05T20:54:28.711+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-05T20:54:28.711+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh 2023 09']
[2024-03-05T20:54:28.716+0000] {subprocess.py:86} INFO - Output:
[2024-03-05T20:54:28.718+0000] {subprocess.py:93} INFO - 
[2024-03-05T20:54:28.718+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/09
[2024-03-05T20:54:28.718+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/09
[2024-03-05T20:54:28.719+0000] {subprocess.py:93} INFO - /opt/***/include/download_bike_dataset.sh: 14: wget: Permission denied
[2024-03-05T20:54:28.719+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-05T20:54:28.724+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-05T20:54:28.726+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230901T000000, start_date=20240305T205428, end_date=20240305T205428
[2024-03-05T20:54:28.732+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task download_dataset (Bash command failed. The command returned a non-zero exit code 1.; 291)
[2024-03-05T20:54:28.737+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T20:54:28.748+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:12:57.625+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:57.631+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:57.632+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T21:12:57.638+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-09-01 00:00:00+00:00
[2024-03-05T21:12:57.641+0000] {standard_task_runner.py:60} INFO - Started process 809 to run task
[2024-03-05T21:12:57.643+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-09-01T00:00:00+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpc_bz54s5']
[2024-03-05T21:12:57.644+0000] {standard_task_runner.py:88} INFO - Job 53: Subtask download_dataset
[2024-03-05T21:12:57.669+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:12:57.690+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:57.691+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:57.695+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230901T000000, start_date=20240305T211257, end_date=20240305T211257
[2024-03-05T21:12:57.701+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 53 for task download_dataset ('str object' has no attribute 'strftime'; 809)
[2024-03-05T21:12:57.735+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:12:57.752+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T13:27:27.058+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2024-03-06T13:27:27.062+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [queued]>
[2024-03-06T13:27:27.063+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-06T13:27:27.070+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-09-01 00:00:00+00:00
[2024-03-06T13:27:27.072+0000] {standard_task_runner.py:60} INFO - Started process 538 to run task
[2024-03-06T13:27:27.074+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-09-01T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpqhzw7k2q']
[2024-03-06T13:27:27.075+0000] {standard_task_runner.py:88} INFO - Job 83: Subtask download_dataset
[2024-03-06T13:27:27.099+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-09-01T00:00:00+00:00 [running]> on host 45431f0a53e1
[2024-03-06T13:27:27.129+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-06T13:27:27.146+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-09-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-01T00:00:00+00:00'
[2024-03-06T13:27:27.146+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-06T13:27:27.147+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 10']
[2024-03-06T13:27:27.152+0000] {subprocess.py:86} INFO - Output:
[2024-03-06T13:27:27.153+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:27:27.153+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/10
[2024-03-06T13:27:27.157+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-06T13:27:27.157+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-06T13:27:28.776+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 11 3197k   11  376k    0     0   304k      0  0:00:10  0:00:01  0:00:09  304k100 3197k  100 3197k    0     0  1974k      0  0:00:01  0:00:01 --:--:-- 1974k
[2024-03-06T13:27:28.778+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:27:28.778+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-06T13:27:28.778+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-06T13:27:28.790+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230901T000000, start_date=20240306T132727, end_date=20240306T132728
[2024-03-06T13:27:28.812+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T13:27:28.822+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
