[2024-03-05T20:54:01.118+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:01.122+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:01.122+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-05T20:54:01.129+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-01-01 00:00:00+00:00
[2024-03-05T20:54:01.132+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2024-03-05T20:54:01.134+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpdbp5c_9k']
[2024-03-05T20:54:01.135+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask download_dataset
[2024-03-05T20:54:01.159+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T20:54:01.184+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-05T20:54:01.200+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2024-03-05T20:54:01.201+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-05T20:54:01.201+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh 2023 01']
[2024-03-05T20:54:01.206+0000] {subprocess.py:86} INFO - Output:
[2024-03-05T20:54:01.207+0000] {subprocess.py:93} INFO - 
[2024-03-05T20:54:01.207+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/01
[2024-03-05T20:54:01.208+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/01
[2024-03-05T20:54:01.208+0000] {subprocess.py:93} INFO - /opt/***/include/download_bike_dataset.sh: 14: wget: Permission denied
[2024-03-05T20:54:01.208+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-05T20:54:01.213+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-05T20:54:01.215+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230101T000000, start_date=20240305T205401, end_date=20240305T205401
[2024-03-05T20:54:01.223+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task download_dataset (Bash command failed. The command returned a non-zero exit code 1.; 220)
[2024-03-05T20:54:01.226+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T20:54:01.238+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:12:30.555+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:30.560+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-05T21:12:30.560+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-03-05T21:12:30.568+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-01-01 00:00:00+00:00
[2024-03-05T21:12:30.571+0000] {standard_task_runner.py:60} INFO - Started process 768 to run task
[2024-03-05T21:12:30.573+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmphsxo91ba']
[2024-03-05T21:12:30.574+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask download_dataset
[2024-03-05T21:12:30.600+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:12:30.624+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:30.624+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:12:30.628+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230101T000000, start_date=20240305T211230, end_date=20240305T211230
[2024-03-05T21:12:30.634+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 38 for task download_dataset ('str object' has no attribute 'strftime'; 768)
[2024-03-05T21:12:30.665+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:12:30.679+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-07T18:18:12.787+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-07T18:18:12.875+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [queued]>
[2024-03-07T18:18:12.875+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2024-03-07T18:18:12.882+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2023-01-01 00:00:00+00:00
[2024-03-07T18:18:12.887+0000] {standard_task_runner.py:60} INFO - Started process 1286 to run task
[2024-03-07T18:18:12.889+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2023-01-01T00:00:00+00:00', '--job-id', '256', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmppqkxdbcv']
[2024-03-07T18:18:12.891+0000] {standard_task_runner.py:88} INFO - Job 256: Subtask download_dataset
[2024-03-07T18:18:12.919+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2023-01-01T00:00:00+00:00 [running]> on host a0c898e5643f
[2024-03-07T18:18:12.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-07T18:18:12.969+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2023-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-01T00:00:00+00:00'
[2024-03-07T18:18:12.970+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-07T18:18:12.971+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2023 02']
[2024-03-07T18:18:12.978+0000] {subprocess.py:86} INFO - Output:
[2024-03-07T18:18:12.980+0000] {subprocess.py:93} INFO - 
[2024-03-07T18:18:12.980+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2023/02
[2024-03-07T18:18:12.984+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-07T18:18:12.984+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-07T18:18:15.800+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0 12 1698k   12  207k    0     0  91201      0  0:00:19  0:00:02  0:00:17 91192100 1698k  100 1698k    0     0   603k      0  0:00:02  0:00:02 --:--:--  603k
[2024-03-07T18:18:15.802+0000] {subprocess.py:93} INFO - Archive:  /opt/***/include/dataset/raw/2023/02/JC-202302-citibike-tripdata.csv.zip
[2024-03-07T18:18:15.842+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/02/JC-202302-citibike-tripdata.csv
[2024-03-07T18:18:15.842+0000] {subprocess.py:93} INFO -   inflating: /opt/***/include/dataset/raw/2023/02/__MACOSX/._JC-202302-citibike-tripdata.csv
[2024-03-07T18:18:16.001+0000] {subprocess.py:93} INFO -   adding: opt/***/include/dataset/raw/2023/02/JC-202302-citibike-tripdata.csv (deflated 84%)
[2024-03-07T18:18:16.002+0000] {subprocess.py:93} INFO - 
[2024-03-07T18:18:16.002+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-07T18:18:16.002+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2023/02/JC-202302-citibike-tripdata.csv.zip
[2024-03-07T18:18:16.003+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-07T18:18:16.016+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20230101T000000, start_date=20240307T181812, end_date=20240307T181816
[2024-03-07T18:18:16.032+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-07T18:18:16.047+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
