[2024-03-05T20:54:45.876+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:45.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-03-05T20:54:45.881+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T20:54:45.887+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2024-02-01 00:00:00+00:00
[2024-03-05T20:54:45.890+0000] {standard_task_runner.py:60} INFO - Started process 331 to run task
[2024-03-05T20:54:45.892+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmprrblmk0m']
[2024-03-05T20:54:45.893+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask download_dataset
[2024-03-05T20:54:45.917+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T20:54:45.942+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-03-05T20:54:45.958+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-03-05T20:54:45.959+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-05T20:54:45.960+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh 2024 02']
[2024-03-05T20:54:45.965+0000] {subprocess.py:86} INFO - Output:
[2024-03-05T20:54:45.966+0000] {subprocess.py:93} INFO - 
[2024-03-05T20:54:45.966+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2024/02
[2024-03-05T20:54:45.966+0000] {subprocess.py:93} INFO - /opt/***/include/dataset/raw/2024/02
[2024-03-05T20:54:45.967+0000] {subprocess.py:93} INFO - /opt/***/include/download_bike_dataset.sh: 14: wget: Permission denied
[2024-03-05T20:54:45.967+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-03-05T20:54:45.972+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-03-05T20:54:45.974+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20240201T000000, start_date=20240305T205445, end_date=20240305T205445
[2024-03-05T20:54:45.980+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 33 for task download_dataset (Bash command failed. The command returned a non-zero exit code 1.; 331)
[2024-03-05T20:54:45.984+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T20:54:45.995+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-05T21:13:16.641+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-03-05T21:13:16.646+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-03-05T21:13:16.646+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-05T21:13:16.653+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2024-02-01 00:00:00+00:00
[2024-03-05T21:13:16.656+0000] {standard_task_runner.py:60} INFO - Started process 834 to run task
[2024-03-05T21:13:16.658+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpq_8amf33']
[2024-03-05T21:13:16.659+0000] {standard_task_runner.py:88} INFO - Job 63: Subtask download_dataset
[2024-03-05T21:13:16.684+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [running]> on host 8277132cfd53
[2024-03-05T21:13:16.710+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'download_dataset', field 'bash_command'. Template: "sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh {{ ds.strftime('%Y') }} {{ ds.strftime('%m') }}"
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:13:16.711+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 174, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 654, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 131, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 859, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'strftime'
[2024-03-05T21:13:16.716+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=citibikedataset, task_id=download_dataset, execution_date=20240201T000000, start_date=20240305T211316, end_date=20240305T211316
[2024-03-05T21:13:16.722+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 63 for task download_dataset ('str object' has no attribute 'strftime'; 834)
[2024-03-05T21:13:16.750+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-05T21:13:16.762+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-06T13:27:52.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-03-06T13:27:52.272+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-03-06T13:27:52.272+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-03-06T13:27:52.279+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): download_dataset> on 2024-02-01 00:00:00+00:00
[2024-03-06T13:27:52.282+0000] {standard_task_runner.py:60} INFO - Started process 574 to run task
[2024-03-06T13:27:52.284+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'citibikedataset', 'download_dataset', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_citibikenyc.py', '--cfg-path', '/tmp/tmpe_yh0e4s']
[2024-03-06T13:27:52.285+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask download_dataset
[2024-03-06T13:27:52.309+0000] {task_command.py:423} INFO - Running <TaskInstance: citibikedataset.download_dataset scheduled__2024-02-01T00:00:00+00:00 [running]> on host 45431f0a53e1
[2024-03-06T13:27:52.339+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207 AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
[2024-03-06T13:27:52.356+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='felipeparfitt' AIRFLOW_CTX_DAG_ID='citibikedataset' AIRFLOW_CTX_TASK_ID='download_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-03-06T13:27:52.357+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-03-06T13:27:52.357+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sh ${AIRFLOW_HOME}/include/download_bike_dataset.sh         2024 03']
[2024-03-06T13:27:52.362+0000] {subprocess.py:86} INFO - Output:
[2024-03-06T13:27:52.363+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:27:52.363+0000] {subprocess.py:93} INFO - Downloading citibike dataset from 2024/03
[2024-03-06T13:27:52.367+0000] {subprocess.py:93} INFO -   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[2024-03-06T13:27:52.367+0000] {subprocess.py:93} INFO -                                  Dload  Upload   Total   Spent    Left  Speed
[2024-03-06T13:27:52.921+0000] {subprocess.py:93} INFO -   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   306    0   306    0     0    552      0 --:--:-- --:--:-- --:--:--   552
[2024-03-06T13:27:52.922+0000] {subprocess.py:93} INFO - 
[2024-03-06T13:27:52.923+0000] {subprocess.py:93} INFO - Download completed successfully!
[2024-03-06T13:27:52.923+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-03-06T13:27:52.937+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=citibikedataset, task_id=download_dataset, execution_date=20240201T000000, start_date=20240306T132752, end_date=20240306T132752
[2024-03-06T13:27:52.978+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-03-06T13:27:52.987+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
